version: "3.8"
services:
  db:
    env_file:
      - .env
    image: mysql:5.7
    ports:
      - "${DB_DOCKER_PORT_EXTERNAL}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql

  cache:
    image: redis:6.0.9-alpine

  app:
    depends_on:
      - db
    build:
#      args:
#        USER_ID: 1000
#        GROUP_ID: 1000
      context: .
      dockerfile: app.dockerfile
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/


  nginx:
    depends_on:
      - app
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html/
      - ./nginx:/etc/nginx/conf.d/

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  dbdata:
    driver: local
